### ISSUE TITLE
docker image name doesn't render correctly in notebook 

### ISSUE THREAD

**Issue by skirui-source** [rapidsai/deployment#173]
CC: @jacobtomlinson 

Two issues I discovered when testing the[ hpo notebook ](https://github.com/rapidsai/deployment/blob/main/source/examples/rapids-sagemaker-hpo/notebook.ipynb) for 23.02 release:
- The notebook file from GH doesn't render `" {{ rapids_container }}"` correctly as it does on the docs page. So I had to manually copy/paste  image name 
- TAG names in DockerHub need to be updated: I was having trouble pulling docker image with these tags : `Error response from daemon: manifest for rapidsai/rapidsai:23.02-cuda11.8-runtime-ubuntu18.04-py3.10 not found: manifest unknown: manifest unknown`

      * rapidsai/rapidsai:23.02-cuda11.8-runtime-ubuntu18.04-py3.10
      * rapidsai/rapidsai:23.02-cuda11.5-runtime-ubuntu18.04-py3.10

^^I think it's because 23.02 is only compatible with Ubuntu 20.04 and cuda 11.5 /11.8 (should be updated in DockerHub)

**Comment by jacobtomlinson** [comment]
Thanks @skirui-source. I'm not sure I understand the second point, the image `rapidsai/rapidsai:23.02-cuda11.8-runtime-ubuntu18.04-py3.10` isn't mentioned anywhere in that notebook. We dropped Ubuntu 18.04 with this release.

The templating issue is an interesting challenge. If a user heads to the GitHub repo and pulls the notebook they will get a notebook with the raw template strings in. If they view the rendered notebook on the website (I expect most users will) there isn't currently any way to download the notebook to run it themselves.

Perhaps we need to add a step to the build which runs the notebook through the templating engine so that it is correctly populated, but then includes the `.ipynb` file in the output too and adds a link to the rendered page so that users can click on it to download the notebook. That way they wouldn't end up on GitHub at all.

**Comment by betatim** [comment]
👍  to adding a way to get the notebook with template strings "rendered". When reviewing a PR this morning I ended up copy&pasting individual cells from the rendered docs preview. It would have been nicer to download the whole notebook.

> Perhaps we need to add a step to the build which runs the notebook through the templating engine so that it is correctly populated, but then includes the `.ipynb` file in the output too and adds a link to the rendered page so that users can click on it to download the notebook. That way they wouldn't end up on GitHub at all.

The idea is that in the repo you'd still only have the version with the template string in it, but in the build output you'd have a version with the string replaced by its actual value? If yes, 👍 . Does ChatGPT know how to create an extension that does this? :D

**Comment by jacobtomlinson** [comment]
> The idea is that in the repo you'd still only have the version with the template string in it, but in the build output you'd have a version with the string replaced by its actual value?

Yup. Me and ChatGPT are on it!

**Comment by skirui-source** [comment]
> Thanks @skirui-source. I'm not sure I understand the second point, the image `rapidsai/rapidsai:23.02-cuda11.8-runtime-ubuntu18.04-py3.10` isn't mentioned anywhere in that notebook. We dropped Ubuntu 18.04 with this release.
> 
> The templating issue is an interesting challenge. If a user heads to the GitHub repo and pulls the notebook they will get a notebook with the raw template strings in. If they view the rendered notebook on the website (I expect most users will) there isn't currently any way to download the notebook to run it themselves.
> 
> Perhaps we need to add a step to the build which runs the notebook through the templating engine so that it is correctly populated, but then includes the `.ipynb` file in the output too and adds a link to the rendered page so that users can click on it to download the notebook. That way they wouldn't end up on GitHub at all.

Apologies just seeing this now, I meant since rapids v23.02 doesn't work with Ubuntu v18.04 anymore, the [dockerhub page](https://hub.docker.com/r/rapidsai/rapidsai) should be upgraded to reflect this
