### ISSUE TITLE
Dask Helm Charts + RAPIDS

### ISSUE THREAD

**Issue by mmccarty** [rapidsai/deployment#7]
Write a documentation page on installing the Dask Helm Chart but with GPUs and RAPIDS.

Preparation:

- Get a Kubernetes cluster (use kind or GKE)
- Install helm
- Try installing the Dask helm chart
  - https://github.com/dask/helm-chart/tree/main/dask
- Check you can get into Jupyter and use the Dask cluster

Documentation outline:

- Get Kubernetes cluster
- Install the Dask helm repo
- Create a config file that sets RAPIDS things
  - Docker image
  - Worker startup command (`dask-cuda-worker`
  - Resources should include a GPU
- Check you can get into Jupyter and use the Dask cluster
- Run through the 10 mins to dask-cudf to show it works

**Comment by isVoid** [comment]
Would love to have a bit more information on step 3: `Create a config file that sets RAPIDS things
`. 

My understanding of `dask-helms-chart` is that it would setup all the scheduler and worker pod with the dask images. There are a couple things we need to do:
1. Replace the dask images with rapids run time images.
2. Add `DISABLE_JUPYTER="true" to worker and scheduler specs.
3. Explicitly request GPU for the scheduler and worker pods.
4. Replace the startup commands for worker pods with `dask-cuda-worker`.

I have a set of working helm-chart derived from dask-helms-chart hosted here: https://github.com/isVoid/helm-chart/tree/rapids/rapids but it looks very much like rapids-helms-chart that just got deprecated. Is there a better way to apply the above changes without having to host a separate set of helm charts?

**Comment by jacobtomlinson** [comment]
Your list is pretty much spot on, we should create an example config file that sets the things you listed. We should verify it works and then users can just copy and paste. The [valyes.yaml](https://github.com/rapidsai/helm-chart/blob/main/rapidsai/values.yaml) file from the deprecated RAPIDS chart is a good place to go for inspiration, but it hasn't been updated since RAPIDS `0.17` so things may not work quite the same now.

Instead of hosting a separate chart we just need [this documentation page](https://github.com/rapidsai/deployment/blob/main/source/tools/kubernetes/dask-helm-chart.md) to be populated with instructions on how to use the Dask Helm Chart with RAPIDS. If you create a config that works and then put it on that page with some explanation around what each option is doing and why we need to do it, and some instructions on how to do it, that would be awesome!
