### ISSUE TITLE
Kubernetes Scheduling Optimization

### ISSUE THREAD

**Issue by mmccarty** [rapidsai/deployment#9]
Best practices regarding number of GPUs per pod.
Efficient node placement w.r.t number of GPUs requested.
```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/deployment/issues/392
- [ ] https://github.com/rapidsai/deployment/issues/393
```

**Comment by jacobtomlinson** [comment]
When creating a GPU Dask cluster with `dask-kubernetes` we typically use the same settings for all Pods, [see the docs for info](https://docs.rapids.ai/deployment/stable/tools/kubernetes/dask-operator/#example-using-kubecluster).

```python
from dask_kubernetes.operator import KubeCluster

cluster = KubeCluster(
    name="rapids-dask",
    image="nvcr.io/nvidia/rapidsai/base:24.04-cuda11.8-py3.10",
    n_workers=3,
    resources={"limits": {"nvidia.com/gpu": "1"}},  # All workers and the scheduler get the same resource settings
    worker_command="dask-cuda-worker",
)
```

While this gets you a functional cluster it may not be the most efficient use of resources, or the most optimal configuarion. There are things we can do to further optimise. It would be good to document these things for advanced users, I expect a good output for this would be to [write a guide for the deployment docs](https://docs.rapids.ai/deployment/stable/guides/). I expect we will need to make modifications to `dask-kubernetes` too in order to make some of these work, so that will need to be done and released before the guide can be published.

The following sections contain possible optimisations. We may not want to do them all, but I'm writing down everything that comes to mind. We should asses the complexity of each one and the expected benefit to weigh up what should be included.

### Use smaller GPU for scheduler Pod

For production workloads users will probably want to use top-tier GPUs for each worker like an A100 or H100. The [scheduler also requires access to a GPU](https://docs.rapids.ai/deployment/stable/guides/scheduler-gpu-requirements/), but it's more of an environment consideration rather than actually needing the GPU for computation or memory. Therefore the scheduler could be run on a T4/L4 in order to reduce cost.

This optimization would involve creating a Kubernetes cluster with multiple node pools with different GPU types, and then using taints/tolerations to ensure Pods land on the right nodes.

### Share a GPU for the scheduler Pod

Another option to optimize the scheduler would be to allow the scheduler to share a GPU with one of the worker Pods. This is more complicated as it would require either enabling MIG, MPS or time-slicing on the cluster, but may be a more optimal solution.

This post [may be useful](https://jacobtomlinson.dev/posts/2023/oversubscribing-gpus-in-kubernetes/) but focuses on time-slicing which is probably the worst of the three sharing options.

### Accelerated networking

We should be able to use [UCX](https://docs.rapids.ai/api/dask-cuda/stable/ucx/) to take advantage of networking protocols and hardware like Infiniband and NVLink. As far as I know only Azure and Oracle cloud support Infiniband, but all providers should support NVLink when using nodes with multiple GPUs. So I would expect the most general documentation we could write would be to talk about NVLink with a TCP fallback in UCX.

### Colocate workers with affinities

We generally make the assumptions that each Pod contains one GPU and one worker. So it would be beneficial on nodes with more than one GPU to have workers colocated to reduce communication overhead. We could do this with affinities to try and group workers as tightly together as possible.

### Multiple GPUs per worker

We might also want to explore breaking the assumption that each Pod has one worker and one GPU. In the above code example `n_workers` directly translates to "number of worker Pods". But we could cofigure the Pod to have multiple GPUs. This means there would be more workers than expected by the user, but it may improve performance.

### Caching images for autoscaling workloads

A popular use case for Kubernetes Dask users is to use the [autoscaler](https://kubernetes.dask.org/en/latest/operator_resources.html#daskautoscaler). One challenge with the autoscaler is if a cluster scales down and then back up again there is no guarantee that the new Pod will be scheduler onto the same node as the one that was previously removed. If the Pod is scheduled on a node that hasn't been used in this Dask cluster before you will have to pay the container pull penalty again. 

To avoid this we may want to include a guide on [prepulling container images](https://jacobtomlinson.dev/posts/2023/quick-and-dirty-way-to-pre-pull-container-images-on-kubernetes/) onto all nodes.

### Container image streaming (GKE only)

In the "Autoscaling multi-tenant Kubernetes Deep-Dive" example notebook [we enable image streaming](https://docs.rapids.ai/deployment/stable/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/#image-steaming-optional) on GKE to ensure Pods start as quickly as possible. As far as I know this is a GKE specific feature where Kubernetes nodes can start running a Pod before the container image has been pulled. Instead it mounts the image from network storage (which is slower but still functional) until the image has been pulled, then it seamlessly switches the mounts to the local cache of the image.

It may be worth breaking this out into a standalong guide rather than leaving it embedded in the example notebook.
